apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ontada-mcp-dev
nameSuffix: -dev
commonLabels:
  app: admin-mfe-dev

resources:
- ../../base/common

replicas:
- name: admin-mfe
  count: 1

patches:
- target:
    kind: Service
  patch: |-
    - op: remove
      path: "/spec/ports/0/targetPort" 

- target:
    kind: Deployment
  patch: |-
    - op: add
      path: /spec/template/spec/volumes
      value:
      - name: fullstory-js-inject
        configMap:
          name: fullstory-js-inject
          items:
            - key: fullstory-js-inject.conf
              path: fullstory-js-inject.conf
    - op: add
      path: /spec/template/spec/containers/0/volumeMounts
      value:
        - name: fullstory-js-inject
          mountPath: /etc/nginx/conf.d/js/fullstory-js-inject.conf
          subPath: fullstory-js-inject.conf
          readOnly: true