apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ontada-mcp-prod
nameSuffix: -prod
commonLabels:
  app: admin-service-prod

# secretGenerator:
# - name: admin-service-secret
#   envs:
#   - secrets.properties
configMapGenerator:
- name: admin-service-config
  envs: 
  - config.properties

resources:
- ../../base/common

replicas:
- name: admin-service
  count: 0