---
apiVersion: v1
kind: Secret
metadata:
  name: admin-service-prod-secret
  namespace: ontada-mcp-prod
type: Opaque
stringData:
  #APP
  SPRING_DATA_MONGODB_URI: "${SPRING_DATA_MONGODB_URI}"
  SPRING_DATA_MONGODB_DATABASE: "${SPRING_DATA_MONGODB_DATABASE}"
  AUTHORIZATION_SERVICE_URL: "${AUTHORIZATION_SERVICE_URL}"
  LIQUIBASE_MONGO_URL_DATABASENAME: "${LIQUIBASE_MONGO_URL_DATABASENAME}"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-service-prod
  # TODO: Change to your teams 
  namespace: ontada-mcp-prod
  labels:
    backstage.io/kubernetes-id: iknowmed-g2-mcp-prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: admin-service-prod
  template:
    metadata:
      labels:
        app: admin-service-prod
        backstage.io/kubernetes-id: iknowmed-g2-mcp-prod
        appContact: 'Sivaranjani_A'
        team: MCP
        github: 'iknowmed-mcp-admin-service'
        appVersion: '${IMAGE_TAG}'
        workflow: '${WORKFLOW_ID}'
    spec:
      containers:
        - name: admin-service-prod
          image: "${DOCKER_REGISTRY}/iknowmed-mcp-admin-service:${IMAGE_TAG}"
          livenessProbe:
            failureThreshold: 6
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            failureThreshold: 6
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          #env:
          #  - name: JAVA_OPTS
          #    value: "-Xms50M -Xmx1524M"
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 250m
              memory: 1Gi
            requests:
              cpu: 50m
              memory: 400Mi
          envFrom:
              - secretRef:
                  name: admin-service-prod-secret
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: "cloud"
          - name: APP_VERSION
            value: "${IMAGE_TAG}"
          - name: JAVA_OPTS
            value: "-XX:MaxRAMPercentage=75"
      imagePullSecrets:
        # TODO: Create this Kubernetes Secret with your jFrog credentials (example in SECRETS.md)
        - name: docker-registry-credentials
      initContainers:
        - name: liquibase
          image: "${DOCKER_REGISTRY}/iknowmed-mcp-admin-service-liquibase:${IMAGE_TAG}"
          command: ["liquibase", "update", "--changeLogFile=changelog/db.changelog_root.xml", "--url=${LIQUIBASE_MONGO_URL_DATABASENAME}"]
          volumeMounts:
          - name: liquibase-changelog-volume
            mountPath: /liquibase/changelog
      volumes:
      - name: liquibase-changelog-volume
        configMap:
          name: admin-service-volume
#           # envFrom:
#           #   - secretRef:
#           #       name: iknowmed-g2-mcp-messaging-services-dev-secret
      restartPolicy: Always
      
---
apiVersion: v1
kind: Service
metadata:
  name: admin-service-prod-svc
  # TODO: Change to your teams namespace
  namespace: ontada-mcp-prod
  labels:
    app: iknowmed-g2-mcp-prod
    backstage.io/kubernetes-id: admin-service-prod
spec:
  ports:
    - protocol: TCP
      port: 8080
  selector:
    app: admin-service-prod
  type: ClusterIP
