
---
apiVersion: v1
kind: Secret
metadata:
  name: admin-service-qa-secret
  namespace: ontada-mcp-qa
type: Opaque
stringData:
  SPRING_DATA_MONGODB_URI: "${SPRING_DATA_MONGODB_URI}"
  SPRING_DATA_MONGODB_DATABASE: "${SPRING_DATA_MONGODB_DATABASE}"
  AUTHORIZATION_SERVICE_URL: "${AUTHORIZATION_SERVICE_URL}"
  LIQUIBASE_MONGO_URL_DATABASENAME: "${LIQUIBASE_MONGO_URL_DATABASENAME}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-service-qa
  namespace: ontada-mcp-qa
  labels:
    backstage.io/kubernetes-id: mcp-admin-qa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-service-qa
  template:
    metadata:
      labels:
        app: admin-service-qa
        backstage.io/kubernetes-id: mcp-admin-qa
        appContact: 'Sivaranjani_A'
        team: MCP
        github: 'iknowmed-mcp-admin-service'
        appVersion: '${IMAGE_TAG}'
        workflow: '${WORKFLOW_ID}'
    spec:
      containers:
        - name: admin-service-qa
          image: "${DOCKER_REGISTRY}/iknowmed-mcp-admin-service:${IMAGE_TAG}"
          livenessProbe:
            failureThreshold: 6
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            failureThreshold: 6
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 1
              memory: 2Gi
            requests:
              cpu: 50m
              memory: 400Mi
          envFrom:
              - secretRef:
                  name: admin-service-qa-secret
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: "cloud"
          - name: JAVA_OPTS
            value: "-XX:MaxRAMPercentage=75"
          - name: APP_VERSION
            value: "${IMAGE_TAG}"
      imagePullSecrets:
        - name: docker-registry-credentials
      initContainers:
        - name: liquibase
          image: "${DOCKER_REGISTRY}/iknowmed-mcp-admin-service-liquibase:${IMAGE_TAG}"
          command: ["liquibase", "update", "--changeLogFile=changelog/db.changelog_root.xml", "--url=${LIQUIBASE_MONGO_URL_DATABASENAME}"]
          volumeMounts:
          - name: liquibase-changelog-volume
            mountPath: /liquibase/changelog
      volumes:
      - name: liquibase-changelog-volume
        configMap:
          name: admin-service-volume
#           # envFrom:
#           #   - secretRef:
#           #       name: iknowmed-g2-mcp-messaging-services-dev-secret
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: admin-service-qa-svc
  namespace: ontada-mcp-qa
  labels:
    app: admin-service-qa
    backstage.io/kubernetes-id: mcp-admin-qa
spec:
  ports:
    - protocol: TCP
      port: 8080
  selector:
    app: admin-service-qa
  type: ClusterIP
