apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ontada-mcp-uat
nameSuffix: -uat
commonLabels:
  app: admin-mfe-uat

resources:
- ../../base/common

replicas:
- name: admin-mfe
  count: 1

patches:
- target:
    kind: Service
  patch: |-
    - op: remove
      path: "/spec/ports/0/targetPort"