nameSuffix:
- path: spec/template/metadata/labels/backstage.io\/kubernetes-id
  kind: Deployment
- path: metadata/labels/backstage.io\/kubernetes-id
  kind: Deployment
- path: /metadata/labels/backstage.io\/kubernetes-id
  kind: Service
- path: spec/template/spec/containers/name
  kind: Deployment
- path: spec/template/spec/containers/name
  kind: Deployment
