apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-service
  labels:
    backstage.io/kubernetes-id: iknowmed-g2-mcp
spec:
  replicas: 3
  template:
    metadata:
      labels:
        backstage.io/kubernetes-id: iknowmed-g2-mcp
        appContact: 'Sivaranjani_A'
        team: MCP
        github: 'iknowmed-mcp-admin-service'
        appVersion: '${DOCKER_IMAGE_TAG}'
        workflow: '${WORKFLOW_ID}'
    spec:
      containers:
        - name: admin-service
          image: "${APP_DOCKER_IMAGE}:${DOCKER_IMAGE_TAG}"
          livenessProbe:
            failureThreshold: 6
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            failureThreshold: 6
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 250m
              memory: 1Gi
            requests:
              cpu: 50m
              memory: 400Mi
          envFrom:
              - configMapRef:
                  name: admin-service-config
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: "cloud"
          - name: APP_VERSION
            value: "${DOCKER_IMAGE_TAG}"
          - name: JAVA_OPTS
            value: "-XX:MaxRAMPercentage=75"
      imagePullSecrets:
        - name: docker-registry-credentials
      initContainers:
        - name: liquibase
          image: "${LIQUIBASE_DOCKER_IMAGE}:${DOCKER_IMAGE_TAG}"
          command: ["liquibase", "update", "--changeLogFile=changelog/db.changelog_root.xml", "--url=${LIQUIBASE_MONGO_URL_DATABASENAME}"]
          volumeMounts:
          - name: liquibase-changelog-volume
            mountPath: /liquibase/changelog
      volumes:
      - name: liquibase-changelog-volume
        configMap:
          name: admin-service-volume
      restartPolicy: Always