apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- service.yml
- deployment.yml
configurations:
- configuration.yml
configMapGenerator:
- name: admin-service-config
  envs: 
  - config.properties