apiVersion: v1
kind: Service
metadata:
  name: admin-mfe-svc
  labels:
    backstage.io/kubernetes-id: iknowmed-mcp-admin
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
