# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
permissions: write-all  

jobs:
  test:
    name: Increment value test
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Check out source code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
      #- name: Increment value
      #  uses: yoichiro/gh-action-increment-value@main
      #  with:
      #    target_directory: './'
      #    target_file: 'build_number.json'
      #    prefix: 'buildNumber":'
      #    suffix: '}'
      #    commit_message: 'Increment the build number to '      
      - name: Increase build
        run: |
          echo $GITHUB_RUN_NUMBER
          echo "### Hello world! :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "100" >> $GITHUB_RUN_NUMBER
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
