name: "Delete workflow"

on:      
  push:
    branches: "test"
jobs:
    wait_job:
      name: "Wait for approval to deploy on Prod environment"
      runs-on: ubuntu-latest
      permissions: write-all
      steps:
        -
          name: Get Code
          uses: actions/checkout@v2
