name: ci_pipeline

on:
  push:
    branches:
      - '*'
  # workflow_dispatch:
  #   inputs:
  #     enabled_veracode_run:
  #       description: 'Execute Veracode scan in release branch'
  #       type: boolean
  #       required: true
  #       default: false

jobs:
  set_env:
    name: Setup Global Environments
    runs-on: ubuntu-la***REMOVED***
    env:
      DOCKER_REGISTRY: "mck-ontada-sre.jfrog.io"
      JFROG_REPO_NAME: "ontada-f***REMOVED***r-service"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

    
      - name: Create Prerelease
        uses: ncipollo/release-action@v1
        with:
          prerelease: true
          tag: v.${{ github.run_number }}-${{ github.run_id }}
          #token: ${{ secrets.GITHUB_TOKEN }}

