name: ci_pipeline

on:
  push:
    branches:
      - '*'
  # workflow_dispatch:
  #   inputs:
  #     enabled_veracode_run:
  #       description: 'Execute Veracode scan in release branch'
  #       type: boolean
  #       required: true
  #       default: false
  
jobs:
  set_env:
    name: Setup Global Environments
    runs-on: ubuntu-la***REMOVED***
    permissions: write-all
    env:
      DOCKER_REGISTRY: "mck-ontada-sre.jfrog.io"
      JFROG_REPO_NAME: "ontada-f***REMOVED***r-service"
      GH_TOKEN: ${{ secrets.SECRET }} #${{ github.token }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Increase build
        run: |
         #echo "BRANCH_NAME=$(echo $GITHUB_REF_NAME)" >> $GITHUB_ENV
         #gh secret list
         #gh secret list -e prod 
         #gh secret delete MASTER_CONTROLLER_NAME -e prod
         #gh secret list -e prod
         gh secret list --jq '.[] | select(.name == "MASTER_CONTROLLER_NAME").name' > /dev/null
         if [ $? -eq 0 ]; then
           echo "Secret exists, deleting..."
           gh secret delete MASTER_CONTROLLER_NAME -e prod
           if [ $? -eq 0 ]; then
             echo "Secret deleted successfully."
           else
             echo "Failed to delete secret."
           fi
         else
           echo "Secret does not exist."
         fi
    
      # - name: Create Prerelease
      #   uses: ncipollo/release-action@v1
      #   with:
      #     #prerelease: true
      #     tag: ***REMOVED***-${{ env.BRANCH_NAME }}-.${{ github.run_number }}-${{ github.run_id }}
      #     makeLa***REMOVED***: true

