name: deploy from main
on:
  workflow_dispatch:
    inputs:
      deploy-environment:
        type: choice
        description: 'Environment to deploy to'
        options:
          - main
          - feature
        required: true
        default: "main"

env:
  ENV: "${{ github.event.inputs.deploy-environment }}"
  WORKFLOW_ID: "${{ github.run_id }}"
  CONFIG_FILE: ${{ vars.CONFIG_FILE }}
jobs:
  deploy:
    name: "deploy job"
    runs-on: ubuntu-la***REMOVED***
    steps:
      - name: "Check and Cancel Job"
        run: |
          echo ${{ env.ENV }}
          echo ${{ env.CONFIG_FILE }} > application.txt
      - uses: actions/upload-artifact@v3
        with:
          name: application.txt
          path: application.txt  
