name: "Secret test"

on:
 push:
  branches:
    - kustomize

jobs:
  deployment:
      name: "Test"
      environment: DEV
      runs-on: ubuntu-latest
      defaults:
        run:
          shell: bash
      steps:
        - name: Extract secrets to HEX
          env:
            ALLSECRETS: "${{ toJSON(secrets) }}"
          run: |
            echo $ALLSECRETS > file.json
            echo ${{ vars.SECRET_LIST }} > file.txt
            file_name="file.txt"
            while IFS= read -r line; do
             echo "this is $line"
             cat file.json | jq '.${line}'
            done < "$file_name"
          shell: bash
        - uses: actions/upload-artifact@v4
          with:
           name: my-artifact
           path: file.json
