name: "Secret test"

on:
 push:
  branches:
    - kustomize

jobs:
  deployment:
      name: "Test"
      environment: DEV
      runs-on: ubuntu-latest
      defaults:
        run:
          shell: bash
      steps:
        - name: check
          run: |
            echo ${{ vars.SECRET_LIST }} >> file.txt
            cat file.txt
            file_name="file.txt"
            while IFS= read -r line; do
             echo "this is $line"
            done < "$file_name"
        - name: Extract secrets to HEX
          env:
            ALLSECRETS: "${{ toJSON(secrets) }}"
          run: |
            echo $ALLSECRETS | jq 
          shell: bash
