name: deploy from main
on:
  workflow_dispatch:
    inputs:
      deploy-environment:
        type: choice
        description: 'Environment to deploy to'
        options:
          - main
          - feature
        required: true
        default: "main"

env:
  ENV: "${{ github.event.inputs.deploy-environment }}"
  WORKFLOW_ID: "${{ github.run_id }}"
jobs:
  deploy:
    name: "deploy job"
    runs-on: ubuntu-la***REMOVED***
    steps:
      - name: "Check and Cancel Job"
        run: |
          echo ${{ env.ENV }}
