name: "Secret test"

on:
 push:
  branches:
    - kustomize

jobs:
  deployment:
      name: "Test"
      environment: DEV
      runs-on: ubuntu-latest
      defaults:
        run:
          shell: bash
      steps:
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_DEBUG: false
          envkey_SECRET_WITH: ${{ secrets.SECRET_WITH }}
          envkey_SECRET_WITHOUT: ${{ secrets.SECRET_WITHOUT }}
          file_name: env.txt
          fail_on_empty: false
          sort_keys: false
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: env.txt
