name: "Secret test"

on:
 push:
  branches:
    - kustomize

jobs:
  deployment:
      name: "Test"
      environment: DEV
      runs-on: ubuntu-latest
      defaults:
        run:
          shell: bash
      steps:
        - name: check
          run: |
            echo ${{ vars.SECRET_LIST }} >> file.txt
            cat file.txt
