name: My workflow

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions: write-all  
jobs:
  build_id:
    name: Increment value ***REMOVED***
    runs-on: ubuntu-la***REMOVED***
    steps:
      - name: 'Set build id'
        id: build_id
        # add a step output `steps.build_id.outputs.id` as the unique id
        run: | 
          echo "::set-output name=id::$(date +%s)"
          export GITHUB_RUN_NUMBER="100" 
          cat GITHUB_ENV
      
