name: My workflow

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions: write-all  
jobs:
  build_id:
    name: Increment value test
    runs-on: ubuntu-latest
    steps:
      - name: 'Set build id'
        id: build_id
        run: | 
          sed -i 's/GITHUB_RUN_NUMBER=.*/GITHUB_RUN_NUMBER=100/' $GITHUB_ENV
          cat $( echo $GITHUB_ENV )
      
