name: My workflow
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions: write-all  
jobs:
  build_id:
    name: Increment value ***REMOVED***
    runs-on: ubuntu-la***REMOVED***
    steps:
      - name: 'Set build id'
        id: build_id 
        run: | 
          echo ${{ github.run_number }}
          write-output $env:run_number
          echo ${{ github.run_number }}
        env:
          run_number: 100
        shell: pwsh
      
