name: My workflow

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions: write-all  
jobs:
  build_id:
    name: Increment value ***REMOVED***
    runs-on: ubuntu-la***REMOVED***
    steps:
      - name: 'Set build id'
        id: build_id
        run: | 
          env | grep GITHUB_RUN_NUMBER
          echo "GITHUB_RUN_NUMBER=100" >> $GITHUB_ENV
          env | grep GITHUB_RUN_NUMBER
          echo $GITHUB_OUTPUT
      
