
name: Deploy Workflow Master
on:      
  workflow_dispatch:
    inputs:
      deploy-environment:
        type: choice
        description: 'Environment to deploy to'
        options:
          - dev
          - prod
          - int
          - qa
          - qa2
          - qa3
          - qa4
          - qa5
          - qa6
          - qa8
          - prod-ecrnow
          - prod-dr
        required: true
        default: 'dev' 

env:
  ENV: "${{ github.event.inputs.deploy-environment }}"
  WORKFLOW_ID: "${{ github.run_id }}"

jobs:
  approval:
    name: "Approval Stage for Master environment"
    runs-on: ubuntu-la***REMOVED***
    steps:
      -
        name: Get Code
        run: |
          echo ${{ env.ENV }}
          echo ${{ env.WORKFLOW_ID }}
