name: "Test Prop"

on:
  push:
    branches:
    - kustomize

env:
  WORKFLOW_FOLDER_NAME: "tmp/apiportal/target"

jobs:

  deployment:
      name: "Test"
      environment: prod
      runs-on: ubuntu-latest
      defaults:
        run:
          shell: bash
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v2

        - name: Make Secret File
          run: |
            echo "SECRET_ONE=`echo ${{ secrets.SECRET_ONE }}`" >> secrets-temp.properties
            echo "List of secrets getting empty value:"
            awk -F'=' '{if ($2=="") print $1}' secrets-temp.properties
            echo "Removing blank secrets"
            awk -F'=' '$2!=""' secrets-temp.properties  > secrets.properties
        - uses: actions/upload-artifact@v4
          with:
            name: my-artifact
            path: ./secrets.properties
