name: POC
on:      
  workflow_dispatch:
    inputs:
      database-update:
        description: 'Select the environment if a database update needed. If not then select "false".'
        type: choice
        required: false
        default: 'false'
        options:
          - 'false'
          - LMDA
          - LMDB
          - LMDC
          - LYNXDEV
          - LMPERF
          - LYNXQA1
          - LYNXALPHA
          - LYNXPERF
          - LYNXPREVIEW
          - LYNXQA

      deploy-environment:
        type: choice
        description: 'Choose environment'
        options:
          - qa
          - alpha
          - perf
          - preview
          - prod
        required: true
        default: 'qa'

      restart-controllers:
        type: boolean
        required: true
        default: false

      only-copy-property-file:
        type: choice
        required: true
        options:
          - 'false'
          - 'true'
env:
    PROPERTY_FILE_CHANGE: "${{ github.event.inputs.only-copy-property-file }}"

jobs:
  First_Workflow:
    name: "Test"
    runs-on: ubuntu-la***REMOVED***
    environment: dev
    steps:
        - name: PROD | Start Master Host Controllers
          if: (${{ github.event.inputs.deploy-environment == 'prod' && github.event.inputs.database-update != 'false' && env.PROPERTY_FILE_CHANGE != 'true' }}) || (${{ github.event.inputs.restart-controllers == 'true' && github.event.inputs.deploy-environment == 'prod' }})  # Need to add one more condition
          run: | 
            echo "Choice work"
