name: "Test install"

on:      
  push:
    branches: main

jobs:
    prerequisite:
      name: "Preparing Deployment"
      runs-on: ubuntu-latest
      defaults:
        run:
          shell: bash 
      container:
        image: mehulsharma20/sqlplus:v7
        options: --user root    
      steps:
        - name: Set Java and Maven
          run: |
            echo "install mvn"
            pacman -Syu --noconfirm
            pacman -S jdk17-openjdk curl maven --noconfirm
            mvn --version


        - name: Database Changes
          run: |
            echo "Running DB Scripts"
            curl -LO https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
            mv jq-linux64 jq
            chmod +x jq
            cp jq /usr/bin
            jq --version
