name: "Test install"

on:      
  push:
    branches: main

jobs:
    prerequisite:
      name: "Preparing Deployment"
      runs-on: ubuntu-latest
      defaults:
        run:
          shell: bash 
      container:
        image: mehulsharma20/sqlplus:v7
        options: --user root    
      steps:
        - name: Set Java and Maven
          run: |
            echo "install mvn"
            cat /etc/os-release
            yum update -y
            yum install openjdk17-jdk -y
            yum install maven -y
            mvn --version


        - name: Database Changes
          run: |
            echo "Running DB Scripts"

            echo "Project Name is: $PROJECT_NAME"
            input="${{ env.TAG_NUMBER}}"
            if [[ $input =~ ^$PROJECT_NAME-(.*?)-([0-9]{4})-([0-9]{2})-([0-9]{2})-([0-9]{6})-([0-9]+) ]]; then
              BRANCH_NAME="${BASH_REMATCH[1]}"
              echo $BRANCH_NAME
              releaseNumber=$(echo "${BASH_REMATCH[1]}" | cut -d- -f 2)
              echo "releaseNumber=`echo ${releaseNumber}`" >> $GITHUB_ENV  
            else
              echo "TAG Number is not matching correct format so not able to get release number."
              exit 1
            fi
            echo "Relase Number is: $releaseNumber"
            echo "Run Database Update Command"
            curl -LO https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
            mv jq-linux64 jq
            chmod +x jq
            cp jq /usr/bin
            jq --version
