name: POC
on:      
  workflow_dispatch:
    inputs:
      release-version:
        description: 'TAG_NUMBER'
        required: true
        type: choice
        default: "lynx-web-0.1020.release_lynx-RELEASE_6.13.4"
        options:
          - test-build-number-master-2023-12-04-080835-580
          - test-build-number-releases-1.1.0-2023-12-04-080835-582
          - test-build-number-releases-1.6.0-2023-12-04-080835-583
          - test-build-number-releases-3.1.0-2023-12-04-080835-584
      restart-controllers:
        type: boolean
        required: true
        default: false

jobs:
  First_Workflow:
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - name: Print false
        if: ${{ githuh.events.inputs.restart-controllers }} == false
        run: | 
          echo "this is ${{ github.events.inputs.restart-controllers }}"
      - name: Print true
        if: ${{ githuh.events.inputs.restart-controllers }} == true
        run: | 
          echo "this is ${{ github.events.inputs.restart-controllers }}"
