name: POC
on:      
  push:
    branches: 
    - main
          
jobs:
  First_Workflow:
    name: "Test"
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: "Make secret file"
        uses: SpicyPizza/create-envfile@v2.0
        with:
          # Add variable name with prefix "envkey_<VARIABLE-NAME>".
          envkey_USER1: ${{ secrets.USER1 }}
          envkey_USER2: ${{ secrets.USER2 }}
          # Below are variable for the module
          file_name: secrets.properties
          fail_on_empty: false
          sort_keys: false
      - name: Print true  
        run: | 
          cat secrets.properties
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: secrets.properties
          
