name: "POC | Final Deployment Workflow"

on:      
  workflow_dispatch:
    inputs:
      rollback-to-release-version:
        description: 'TAG_NUMBER'
        required: true
        type: string
        default: "lynx-releases-6.2.2-2023-12-04-080835-02"
        options:
          - lynx-releases-6.14.2-2023-12-04-080835-02
          - lynx-releases-6.14.1-2023-12-04-080835-02
          - lynx-releases-6.2.2-2023-12-04-080835-02
          - lynx-releases-6.2.1-2023-12-04-080835-01
          - lynx-releases-6.13.4-2023-12-04-080835-589
          - lynx-releases-1.1.0-2023-12-04-080835-581
          - lynx-releases-1.1.3-2023-12-04-080835-582
          - lynx-releases-1.1.3-2023-12-04-080835-582

env:
  TAG_NUMBER: "${{ github.event.inputs.rollback-to-release-version }}"
jobs:
    prerequisite:
      name: "Preparing Deployment in ${{ github.event.inputs.deploy-environment }} for tag : ${{ github.event.inputs.rollback-to-release-version }}"
      environment: ${{ github.event.inputs.deploy-environment }}
      runs-on: ubuntu-latest   #kube-deploy
      defaults:
        run:
          shell: bash
      steps:
        - name: echo cmd
          run: echo "${{ env.TAG_NUMBER }}"
