name: Predefined function
on: push
jobs:
  job1:
    runs-on: ubuntu-la***REMOVED***
    steps:
      - id: step1
        run: "echo ***REMOVED***=hello >> $GITHUB_OUTPUT"
      - name: step2
        if: contains(steps.step1.outputs.***REMOVED***, 'hello')
        run: echo is executed
      - name: step3
        if: contains(steps.step1.outputs.***REMOVED***, 'bye')
        run: echo not executed
  job2:
    runs-on: ubuntu-la***REMOVED***
    steps:
      - name: step2
        if: contains(steps.step1.outputs.***REMOVED***, 'hello')
        run: echo is executed
      - name: step3
        if: contains(steps.step1.outputs.***REMOVED***, 'bye')
        run: echo not executed
