name: Test in main
on:
  workflow_dispatch:
    inputs:
      branch-name:
        type: choice
        description: 'Environment to deploy to'
        options:
          - main
          - prod-dr
        required: true
        default: 'main'
env:
  BRANCH_NAME: "${{ github.event.inputs.branch-name }}"
jobs:
  test:
    name: "Echo branch name"
    runs-on: ubuntu-latest
    steps:
      -
        name: Print branch name
        run: |
          if [ "${{ github.event.inputs.branch-name }}" == "prod-dr" ]; then
            export BRANCH_NAME="main"
          fi
          echo ${{ env.BRANCH_NAME }}
  post:
    name: "Post job"
    runs-on: ubuntu-latest
    steps:
      -
        name: Print branch name
        run: echo ${{ env.BRANCH_NAME }}        
