name: Predefined function
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - id: step1
        run: echo "num=success" >> $GITHUB_OUTPUT
      - id: step2
        run: sleep 60 ; echo "step2" 
    outputs: 
      num: ${{ steps.step1.outputs.num }}
  job2:
    runs-on: ubuntu-latest
    env: 
      num: ${{ needs.step1.outputs.num }}
    steps:
      - id: step3
        run: echo "step3" && echo "this is ${{ job.job1.step2.status }}"
      - id: step4
        if: ${{ env.num == "success" }}
        run: echo "step4"
