name: Predefined function
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - id: step1
        run: echo "step1"
      - id: step2
        run: echo "step2" 
  job2:
    runs-on: ubuntu-latest
    steps:
      - id: step3
        run: echo "step3"
      - id: step4
        if: ${{ job.status == 'success' }} 
        run: echo "step4"
