name: Deploy Workflow
on:
  workflow_dispatch:
    inputs:
      choose-service:
        description: 'Please choose batch job'
        required: true
        type: choice
        options:
        - none
        - invitation-expiry-populate
        - invitation-expiry-process
        default: 'none' 

      all-services:
        description: 'select all services at once'
        type: boolean
        required: true
        default: false

env:
  SERVICE_NAME: "${{ github.event.inputs.choose-service }}"
  ALL_SERVICES: "${{ github.event.inputs.all-services }}"
  ENV: "dev"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Test
      run: |
        if [ ${{ env.ALL_SERVICES }} == false ]; then
          echo $SERVICE_NAME

        elif [ ${{ env.ALL_SERVICES }} == true ]; then
          set -ex
          echo "${{ vars.ALL_CRONJOB_NAMES }}" > all-cronjobs.txt
          sed -i 's/\r//g'  all-cronjobs.txt
          cat all-cronjobs.txt
          IFS=''
          while read line; do
              echo $line
          done < all-cronjobs.txt
        fi
