name: Predefined function
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_VAR1: ${{ secrets.VAR1 }}
          envkey_VAR2: ${{ secrets.VAR2 }}
          envkey_VAR3: ${{ secrets.VAR3 }}
          # Below are variable for the module
          file_name: secrets.properties
          fail_on_empty: false
          sort_keys: false
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: secrets.properties
