name: Predefined function
on: push
jobs:
  job1:
    runs-on: ubuntu-la***REMOVED***
    steps:
      - id: step1
        run: echo "step1"
      - id: step2
        run: sleep 60 ; echo "step2" 
  job2:
    runs-on: ubuntu-la***REMOVED***
    steps:
      - id: step3
        run: echo "step3"
      - id: step4
        if: ${{ job.job1.step2.status == 'success' }} 
        run: echo "step4"
