name: Multi-Choice Options

on:
  workflow_dispatch:
    inputs:
      choice:
        description: 'Select an option'
        required: true
        default: 'option1'
        choices:
          - option1
          - option2
          - option3
jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run the selected option
        run: |
          if [[ "${{ inputs.choice }}" == 'option1' ]]; then
            echo "Option 1 chosen"
          elif [[ "${{ inputs.choice }}" == 'option2' ]]; then
            echo "Option 2 chosen"
          elif [[ "${{ inputs.choice }}" == 'option3' ]]; then
            echo "Option 3 chosen"
          fi
