name: Predefined function
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - id: step1
        run: "echo OUTPUT_JOB1=hello >> $GITHUB_OUTPUT"
    outputs:
      OUTPUT_JOB1: ${{ steps.step1.outputs.OUTPUT_JOB1 }}
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: step2
        if: contains(needs.job1.outputs.OUTPUT_JOB1, 'hello')
        run: echo is executed
      - name: step3
        if: contains(steps.step1.outputs.test, 'bye')
        run: echo not executed
      - name: step4
        run: echo ${{ needs.job1.outputs.OUTPUT_JOB1 }}
