name: Checkbox Options
on:
  workflow_dispatch:
    inputs:
      print_tags:
        description: 'True to print to STDOUT'
        required: true
        type: choices
        options:
        - hello
        - by
        - seeu
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run the selected options
        run: |
          if [[ "${{ inputs.option1 }}" == 'true' ]]; then
            echo "Option 1 checked"
          fi
          if [[ "${{ inputs.option2 }}" == 'true' ]]; then
            echo "Option 2 checked"
          fi
          if [[ "${{ inputs.option3 }}" == 'true' ]]; then
            echo "Option 3 checked"
          fi
